name: Monitoramento de Logs

on:
  schedule:
    - cron: '*/30 * * * *'  # Executa a cada 30 minutos
  workflow_dispatch:        # Permite execução manual

jobs:
  executar_script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        run: |
          sudo apt update
          sudo apt install -y python3

      - name: Executar script de monitoramento
        run: python3 monitoramento_logs.py

      - name: Salvando CSV com logs
        uses: actions/upload-artifact@v4
        with:
          name: logs_csv
          path: eventos_logs.csv
